### ISSUE TITLE
对xdoc的项目的依赖是否可以彻底解耦

### ISSUE THREAD

**Issue by lotosbin** [xyting/RigoFunc.ApiCore#2]
```C#
   // Bad Request
                context.HttpContext.Response.StatusCode = 400;

                var json = new JObject();
                json.Add("ErrorMessage", exception.Message);
                if (exception is ArgumentNullException && env.IsDevelopment()) {
                    json.Add("ApiDoc", GetApiDoc(context));
                }

                // Json result.
                context.Result = new JsonResult(json);
            }
            catch {
                base.OnException(context);
            }
        }

```
目前项目中唯一的依赖，
可以在ｘｄｏｃ项目中新增ExceptionFilterAttribute（排序在最后），来处理文档相关的内容。
@xyting

**Comment by xyting** [comment]
@lotosbin  ApiCore准备移掉XDoc，同时，XDoc会结合ApiExplorer，开发计划是这个周五完成，完成之后，通过DI方式启用文档功能

**Comment by xyting** [comment]
[Love.Net Team](https://github.com/lovedotnet/) had developed a new generate API documentation toolchain for ASP.NET Core.  see [Love.Net.Help](https://github.com/lovedotnet/Love.Net.Help), and the commit [b9fe395](https://github.com/xyting/RigoFunc.ApiCore/commit/b9fe395730e7072aa14727d753c79f6ff83bd72c) hand remove the [RigoFunc.XDoc](https://github.com/xyting/RigoFunc.XDoc) dependency so close this.
